### ISSUE TITLE
Custom Theme - User Names

### ISSUE THREAD

**Issue by KGEvans** [Nuvm/NCS#1]
Hey, not 100% on if this is a bug, or what you designed it to be.

The names of chat users when using the Custom Theme of NCS gives them a 'glow' kind of texture. I find this rather hard to read names at times. If this is how it is designed to be, is it possible to have an option to disable this?

That is all. I'm looking forward to what else you have to offer and am willing to report any future bugs I find. -KGEvans

**Comment by Nuvm** [comment]
Hi KGEvans,

It's not a bug. It's part of the custom theme CSxKING has made (question his intentions by yourself :P). Thank you, though, for taking your time to come here to tell us about it ;)

**Comment by ImExiled** [comment]
Heyo, thought I would add here since people seem to question it.... The glow used to be a feature I wanted early on in NCS. Its no longer something I want, and plan to remove it shortly. Sorry about that, and for my super late reply.
