### ISSUE TITLE
Chatting bug with 1.0.0

### ISSUE THREAD

**Issue by TomyKalm** [Nuvm/NCS#10]
Hello!

There is one nasty bugs with the NCS Christmas 1.0.0 version (I am not sure if this bug is known or not): 

While NCS is enabled (bookmark) I can't click on "Type a message and hit enter" and type. http://imgur.com/x3KN2Bz

**Comment by WindWalk12** [comment]
That happens if you got the AFK on

**Comment by TomyKalm** [comment]
Thank you!
