### ISSUE TITLE
Ncs button

### ISSUE THREAD

**Issue by Summers-Rain** [Nuvm/NCS#3]
Seems like when the title gets to long this happens. 
http://imgur.com/fUz1pQc

**Comment by ImExiled** [comment]
Yeah we noticed that. I think we'll either limit how long the title can get before going to another line or make it smaller. Keep it out of the way. Heck we may just move the button to the bottom of the NCS menu.

**Comment by Summers-Rain** [comment]
aight

**Comment by ImExiled** [comment]
Took a year and a half (not literally lol) but this has finally been fixed!! :D
