### ISSUE TITLE
Mentions

### ISSUE THREAD

**Issue by Sarayalth** [Nuvm/NCS#4]
This is more a request than a bug...

Well, it's a good idea an option to disable the mentions sound?
Sometimes i saw people in the room doing homework or something and only want the music, not the mention sound.

**Comment by ImExiled** [comment]
Sounds cool! Sorry its taking so long to reply to these things. I'll see if I can get Nuvm to implement it! :D

**Comment by Nuvm** [comment]
As far as I'm concerned, this will be implemented in the next updates
of Alpha itself.
